# Generated by Django 4.1 on 2023-04-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_qte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qte',
            field=models.IntegerField(default=10),
        ),
    ]
