# Generated by Django 4.1 on 2023-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usermodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='type',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
