# Generated by Django 4.1 on 2023-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='type',
            field=models.CharField(default='seller', max_length=255),
        ),
    ]
